FROM mysql:5.7-debian

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
ADD infrastructure/mysql/mysql.cnf /etc/mysql/mysql.conf.d/mysql.cnf

# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .
